version: '3'
services:
  yddt:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    container_name: testdb
    restart: always
#    volumes:
#      - ./migration_scripts/app/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
#    env_file:
#      - .env-db
    healthcheck:
      test: pg_isready
